import { useEffect,useState } from 'react';
import { ConnectionBadge } from '../components/ConnectionBadge.js';
import { MessageBubble } from '../components/MessageBubble.js';
import { readLocalVisibleMessages,reconcileChat,sendTextMessage,type VisibleMessage } from '../flows/messages.js';
import { connectRealtime } from '../realtime/socket.js';
import { getUnlockedPin,setUnlockedPin,loadProfile } from '../local/session.js';
import { unlockDeviceProfile } from '../local/keystore.js';
type SelectedMember={id:string;displayName:string};
export function FamilyChatScreen(_props:{selectedMember?:SelectedMember|null}){const [profile,setProfile]=useState<Awaited<ReturnType<typeof loadProfile>>>(null);const [inputPin,setInputPin]=useState('');const [readyPin,setReadyPin]=useState(getUnlockedPin()??'');const [draft,setDraft]=useState('');const [messages,setMessages]=useState<VisibleMessage[]>([]);const [connection,setConnection]=useState<'connecting'|'online'|'offline'>('offline');const [error,setError]=useState('');useEffect(()=>{void loadProfile().then(setProfile);},[]);useEffect(()=>{if(!profile||!readyPin)return;let stop=()=>{};void readLocalVisibleMessages(profile.familyChatId,readyPin).then(setMessages).catch(()=>{});const reconcile=async()=>{const incoming=await reconcileChat(profile.familyChatId,readyPin);if(incoming.length)setMessages(await readLocalVisibleMessages(profile.familyChatId,readyPin));};stop=connectRealtime({chatId:profile.familyChatId,onReconcile:reconcile,onState:setConnection});return()=>stop();},[profile,readyPin]);if(!profile)return null;if(!readyPin)return <main className="center-card"><h1>Разблокировать</h1><form className="form" onSubmit={async e=>{e.preventDefault();try{await unlockDeviceProfile(inputPin);setUnlockedPin(inputPin);setReadyPin(inputPin);setError('');}catch(err){setError(err instanceof Error?err.message:'Неверный PIN');}}}><label>PIN<input inputMode="numeric" pattern="[0-9]{6,}" value={inputPin} onChange={e=>setInputPin(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button className="primary">Открыть чат</button></form></main>;const activeProfile=profile;async function send(e:React.FormEvent){e.preventDefault();const text=draft.trim();if(!text)return;setDraft('');try{await sendTextMessage(text,readyPin);setMessages(await readLocalVisibleMessages(activeProfile.familyChatId,readyPin));}catch(err){setError(err instanceof Error?err.message:'Не отправлено');setDraft(text);}}return <section className="chat"><header className="chat-header"><div><strong>{activeProfile.familyDisplayName??'Наша семья'}</strong><div className="hint">Сквозное шифрование</div></div><ConnectionBadge state={connection}/></header><div className="messages">{messages.map(m=><MessageBubble key={m.messageId} message={m} mine={m.senderDeviceId===activeProfile.deviceId}/>)}</div>{error&&<div className="error-inline">{error}</div>}<form className="composer" onSubmit={send}><textarea aria-label="Сообщение" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Сообщение семье" rows={1}/><button className="send" aria-label="Отправить">➤</button></form></section>;}
