import { decryptTextMessage, encryptTextMessage } from '@family-messenger/crypto';
import type { StoredMessageEnvelope } from '@family-messenger/protocol';
import { api } from '../api/client.js';
import { getDb } from '../local/db.js';
import { loadChatKey } from '../local/keystore.js';
import { loadProfile } from '../local/session.js';
import { rotateChatKey, syncCurrentChatKey } from './key-rotation.js';

export type VisibleMessage={messageId:string;text:string;sentAt:string;senderDeviceId:string;sequence:string};
async function persist(items:StoredMessageEnvelope[]){const db=await getDb();const tx=db.transaction('messages','readwrite');for(const item of items)await tx.store.put(item);await tx.done;}
async function sendOnce(text:string,pin:string,targetChatId:string,deviceId:string){const current=await loadChatKey(targetChatId,pin);const envelope=await encryptTextMessage({messageId:crypto.randomUUID(),chatId:targetChatId,senderDeviceId:deviceId,keyVersion:current.keyVersion,key:current.key,payload:{kind:'text',text,sentAt:new Date().toISOString()}});const stored=await api<StoredMessageEnvelope>(`/v1/chats/${targetChatId}/messages`,{method:'POST',body:JSON.stringify(envelope)});await persist([stored]);const payload=await decryptTextMessage(stored,current.key);return {messageId:stored.messageId,text:payload.text,sentAt:payload.sentAt,senderDeviceId:stored.senderDeviceId,sequence:stored.sequence} satisfies VisibleMessage;}
export async function sendTextMessage(text:string,pin:string,chatId?:string){const profile=await loadProfile();if(!profile||profile.status!=='active')throw new Error('active_profile_required');const targetChatId=chatId??profile.familyChatId;try{return await sendOnce(text,pin,targetChatId,profile.deviceId);}catch(error){if(!(error instanceof Error)||error.message!=='key_rotation_required')throw error;await rotateChatKey(targetChatId,pin);return sendOnce(text,pin,targetChatId,profile.deviceId);}}
async function keyForEnvelope(chatId:string,pin:string,item:StoredMessageEnvelope){try{return await loadChatKey(chatId,pin,item.keyVersion);}catch(error){const current=await loadChatKey(chatId,pin).catch(()=>null);if(!current||item.keyVersion>current.keyVersion){await syncCurrentChatKey(chatId,pin);return loadChatKey(chatId,pin,item.keyVersion);}throw error;}}
export async function reconcileChat(chatId:string,pin:string){const db=await getDb();const cursor=(await db.get('sync',chatId))?.cursor??'0';const result=await api<{items:StoredMessageEnvelope[];nextCursor:string}>(`/v1/chats/${chatId}/messages?after=${encodeURIComponent(cursor)}&limit=100`);await persist(result.items);await db.put('sync',{chatId,cursor:result.nextCursor});const visible:VisibleMessage[]=[];for(const item of result.items){const key=await keyForEnvelope(chatId,pin,item);const payload=await decryptTextMessage(item,key.key);visible.push({messageId:item.messageId,text:payload.text,sentAt:payload.sentAt,senderDeviceId:item.senderDeviceId,sequence:item.sequence});}return visible;}
export async function readLocalVisibleMessages(chatId:string,pin:string){const db=await getDb();const items=await db.getAllFromIndex('messages','chatId',chatId);items.sort((a,b)=>{const av=BigInt(a.sequence),bv=BigInt(b.sequence);return av<bv?-1:av>bv?1:0;});const out:VisibleMessage[]=[];for(const item of items){const key=await loadChatKey(chatId,pin,item.keyVersion);const payload=await decryptTextMessage(item,key.key);out.push({messageId:item.messageId,text:payload.text,sentAt:payload.sentAt,senderDeviceId:item.senderDeviceId,sequence:item.sequence});}return out;}
